/**
 * The framework's own meta-schemas, carried inside the portal's own bundle.
 *
 * GENERATED by `framework/portal/scripts/build-embedded-schemas.mjs` from
 * `solutions/metaframework/product/specification/datamodel/<name>/schema.json`.
 * Edit those and re-run it. Do not edit this file: its generator's test
 * re-renders it on every `npm test` and compares byte for byte, so a hand-edit
 * is a red suite rather than a copy that has quietly stopped being one.
 *
 * These eight exist here because a catalog that is not this repository has no
 * `metaframework` solution, and therefore nothing to answer the `$schema` URL
 * every artifact it holds declares. Identity stays global and singular on the
 * canonical host; retrieval becomes local *everywhere*, not just here
 * (`src/app/schemas/[...path]/route.ts`).
 *
 * The key is the catalog-relative directory the document is served at, which is
 * its `$id` minus the canonical host — checked rather than assumed, by the
 * generator's inherited refusal to embed a document whose `$id` disagrees with
 * where it would be served.
 */

/**
 * Look-ups are keyed by a path taken from a request, so a miss is the ordinary
 * case and the value type says so.
 *
 * The table has no prototype, which is what makes that type true. A plain object
 * literal answers `constructor` and `toString` with a function, so a request
 * for one of those names would hand a function to code the type promised a
 * string. The route's SRN gate refuses those paths long before this table is
 * reached and `Object.create(null)` is therefore belt and braces — but a table
 * whose declared type is honest on its own does not depend on a gate two blocks
 * away staying exactly as strict as it is today.
 */
export const EMBEDDED_META_SCHEMAS: Readonly<Record<string, string | undefined>> =
  Object.assign(Object.create(null), {
    'metaframework/product/specification/datamodel/config-document': `{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.metaframework.dev/metaframework/product/specification/datamodel/config-document",
  "x-srn": "srn://metaframework/product/specification/datamodel/config-document",
  "title": "Config document",
  "description": "config.yaml — the configuration surface an environment provides: which keys it declares and where their values come from. It never carries a secret value. Specified in framework/spec/kinds/environment.md and read by framework/portal/src/lib/environment/environment.ts, which is the executable copy of the same rules.",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string",
      "minLength": 1,
      "description": "The dialect discriminator (0015-artifact-dialects); the canonical value is this schema's own $id. Deliberately unpinned rather than const: a value naming some other dialect is W_ARTIFACT_DIALECT, a warning, read as the legacy dialect and never broken — a const here would restate that ruling as a hard rejection in the one place a severity cannot be relaxed. The loader strips the key once it has recorded the dialect, so nothing downstream ever sees it — and the reader that now parses this file inherited that guarantee without having to know about it, which is what the stripping was for."
    },
    "config": {
      "type": "array",
      "items": { "$ref": "#/$defs/entry" },
      "description": "REQUIRED if the file exists. The whole top level: there is no environment-wide preamble and no grouping key, because a key's scope is carried by its own \`for:\` and nothing else."
    }
  },
  "required": ["config"],
  "patternProperties": {
    "^x-": {
      "description": "The escape hatch reaches into this artifact, at the top level and inside entries. Tolerated and ignored by the portal; any other unknown key is E_ENV_CONFIG_SCHEMA. No top-level version: both environment siblings are part of the entity's version snapshot and carry no version field of their own."
    }
  },
  "additionalProperties": false,
  "$defs": {
    "entry": {
      "type": "object",
      "description": "One declared key. Unique per (key, for) pair — a fact about the list, and therefore not statable here: uniqueItems compares whole entries, so two declarations of one key differing only in their description are distinct to a validator.",
      "properties": {
        "key": {
          "type": "string",
          "pattern": "^[A-Z][A-Z0-9_]*$",
          "description": "SCREAMING_SNAKE_CASE on purpose, and not kebab-case: config keys belong to the runtime's namespace, not to the catalog's. Env-var casing is what an operator copy-pastes, and it makes \`grep -r DATABASE_URL solutions/\` unambiguous against SRN segments, which are kebab-case by grammar."
        },
        "for": {
          "$ref": "#/$defs/srn-ref",
          "description": "The component or product the key applies to (E_ENV_TARGET_KIND). Absent means environment-wide. A \`for:\` naming a component that does not run in this environment is dead configuration, W_ENV_CONFIG_ORPHAN."
        },
        "secret": {
          "type": "boolean",
          "default": false,
          "description": "Marks the value as sensitive. It is the discriminator between the two shapes an entry may take, and the only field here that changes which other fields are legal."
        },
        "value": {
          "type": ["string", "number", "boolean"],
          "description": "One scalar: the literal value, for a key that has one in the open. FORBIDDEN when secret is true (E_ENV_SECRET_VALUE) — at any status, in any environment, because this file is reviewable in git and anything in it is public. The field was typed \`string\` alone until environment.md v6 widened it to any scalar, which is additive in the sense evolution.md means: every document that validated against the narrower type still validates, so the dialect, its URL and its discriminator string are unchanged and only this meta-schema's own version moves. A list is not a scalar and is not admitted — that is a delimiter convention the runtime owns, and a contract types it as a string with a pattern. The value is checked against the key's own subschema in the component's usage:config contract (E_ENV_CONFIG_VALUE), which is where a type narrower than this one is stated."
        },
        "source": {
          "type": "string",
          "minLength": 1,
          "description": "A locator for the value and never the value: vault:kv/acme/production/checkout#database-url. Free-form but stable. REQUIRED when secret is true."
        },
        "description": {
          "type": "string",
          "minLength": 1,
          "maxLength": 200,
          "pattern": "^[^\\\\n]+$",
          "description": "One line: what the key controls."
        }
      },
      "required": ["key"],
      "patternProperties": { "^x-": {} },
      "additionalProperties": false,
      "if": {
        "properties": { "secret": { "const": true } },
        "required": ["secret"]
      },
      "then": {
        "description": "The three-layer rule, stated where a schema can hold it: the contract lives in git, the declaration lives in git, and the value lives only in a vault or at deploy time. Keyed on \`secret: true\` rather than on the presence of \`secret\`, so an explicit \`secret: false\` is the ordinary shape and not a special case.",
        "required": ["source"],
        "not": { "required": ["value"] }
      }
    },
    "srn-ref": {
      "type": "string",
      "minLength": 1,
      "description": "An ordinary SRN reference. Relative forms resolve against the artifact's own URI, srn://{solution}/environment/{name}/config.yaml, so the solution-absolute form is strongly preferred. An artifact suffix is refused (ENV11): \`for:\` names an entity, and an artifact has no kind."
    }
  }
}
`,
    'metaframework/product/specification/datamodel/entity-frontmatter': `{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.metaframework.dev/metaframework/product/specification/datamodel/entity-frontmatter",
  "x-srn": "srn://metaframework/product/specification/datamodel/entity-frontmatter",
  "title": "Entity frontmatter",
  "description": "The YAML block at the top of every entity index.md: the common contract from framework/spec/frontmatter.md plus the fields the entity's kind document adds. Modelled as a discriminated union on \`kind\`, which is how framework/portal/src/lib/catalog/frontmatter.ts implements it (commonFrontmatterSchema plus KIND_FRONTMATTER).",
  "type": "object",
  "properties": {
    "name": {
      "$ref": "#/$defs/kebab",
      "description": "MUST equal the entity's directory name (E_FM_NAME_MISMATCH)."
    },
    "kind": {
      "type": "string",
      "enum": [
        "solution",
        "product",
        "component",
        "datamodel",
        "protocol",
        "actor",
        "environment",
        "adr",
        "requirement",
        "capability",
        "journey",
        "metric"
      ],
      "description": "The ontology, in adoption order: the founding nine, then \`capability\`, \`journey\` and \`metric\` (decision-record amendment 2026-08-20-a). Closed but no longer fixed — it grows by appending, never by re-cutting, so nothing that was a kind stops being one. MUST equal the kind bucket the directory sits in (E_FM_KIND_LOCATION); the solution root is the only entity with no bucket."
    },
    "version": {
      "type": "integer",
      "minimum": 1,
      "description": "Integer, never a string. Bumped on every content change per evolution.md; a change to \`status\` alone is exempt."
    },
    "title": { "type": "string", "minLength": 1, "maxLength": 80 },
    "summary": { "$ref": "#/$defs/one-line" },
    "status": {
      "type": "string",
      "enum": ["draft", "review", "approved", "deprecated"],
      "description": "Document lifecycle — is this description written and reviewed. Never the described thing's real-world stage."
    },
    "owner": {
      "type": "string",
      "minLength": 1,
      "description": "Free-form responsible handle. No registry of handles exists; nothing validates it."
    },
    "relations": { "$ref": "#/$defs/relations" },
    "tags": {
      "type": "array",
      "items": { "$ref": "#/$defs/kebab" },
      "description": "Free navigation facets. No semantics attached."
    }
  },
  "required": ["name", "kind", "version", "title", "summary", "status"],
  "patternProperties": {
    "^x-": {
      "description": "The escape hatch for local experimentation. Tolerated, ignored by the portal."
    }
  },
  "oneOf": [
    {
      "title": "solution",
      "properties": {
        "kind": { "const": "solution" },
        "vision": { "type": "string", "minLength": 1, "maxLength": 1000 },
        "scope": {
          "type": "object",
          "properties": {
            "in": { "type": "array", "items": { "$ref": "#/$defs/one-line" } },
            "out": { "type": "array", "items": { "$ref": "#/$defs/one-line" } }
          },
          "required": ["in"]
        },
        "contacts": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "role": { "$ref": "#/$defs/kebab" },
              "handle": { "type": "string", "minLength": 1 },
              "channel": { "type": "string" }
            },
            "required": ["role", "handle"]
          }
        }
      },
      "required": ["vision"]
    },
    {
      "title": "product",
      "properties": {
        "kind": { "const": "product" },
        "lifecycle": {
          "type": "string",
          "enum": ["concept", "incubating", "active", "maintenance", "sunset", "retired"],
          "description": "The product in the world, as opposed to \`status\`, which is the document."
        },
        "primary-actors": {
          "type": "array",
          "items": { "$ref": "#/$defs/srn-ref" },
          "description": "A kind field rather than an edge, because no v1 edge type accepts an actor target."
        }
      },
      "required": ["lifecycle"]
    },
    {
      "title": "component",
      "properties": {
        "kind": { "const": "component" },
        "component-type": {
          "type": "string",
          "enum": [
            "service",
            "library",
            "ui",
            "job",
            "datastore",
            "gateway",
            "external",
            "content",
            "application",
            "specification"
          ],
          "description": "Adoption order: the original seven, then \`content\`, \`application\` and \`specification\` (decision-record amendment 2026-08-20-g). If no value fits, pick the nearest and record the nuance in an \`x-\` field; inventing an eleventh is E_FM_SCHEMA."
        },
        "lifecycle": {
          "type": "string",
          "enum": ["planned", "in-development", "released", "sunset", "retired"],
          "description": "Delivery state of the component in the world, as opposed to \`status\`, which is the review state of this document. The two axes cross and every cell is legal. The value set is deliberately not product's: a component is built and shipped rather than positioned in a portfolio, so \`lifecycle: incubating\` on a component is E_FM_SCHEMA even though it is valid on a product."
        },
        "criticality": {
          "type": "integer",
          "minimum": 1,
          "maximum": 4,
          "description": "Blast radius and review priority. OPTIONAL and defaultless on purpose: absent means \\"not assessed\\", never tier 4, and the value carries no SLA semantics."
        }
      },
      "required": ["component-type", "lifecycle"]
    },
    {
      "title": "datamodel",
      "properties": {
        "kind": { "const": "datamodel" },
        "usage": {
          "type": "string",
          "enum": ["storage", "exchange", "both", "config"],
          "description": "Where instances of this model live. \`config\` is the fourth value: a component's configuration contract, read out of a process environment. It turns on a discipline this schema does not state — flat SCREAMING_SNAKE scalar properties, \`writeOnly\` secrets, at most one concrete contract per bucket — which lives in the schema document, not the frontmatter (framework/spec/kinds/datamodel.md)."
        },
        "abstract": { "type": "boolean", "default": false }
      },
      "required": ["usage"]
    },
    {
      "title": "protocol",
      "properties": {
        "kind": { "const": "protocol" },
        "style": { "type": "string", "enum": ["point-to-point", "bus", "request-response"] },
        "participants": {
          "type": "array",
          "minItems": 2,
          "items": {
            "type": "object",
            "properties": {
              "alias": { "$ref": "#/$defs/kebab", "maxLength": 32 },
              "ref": { "$ref": "#/$defs/srn-ref" },
              "role": { "$ref": "#/$defs/kebab", "maxLength": 32 }
            },
            "required": ["alias", "ref"]
          },
          "description": "Authoritative for the workflow alias namespace and for the NCA that fixes the directory — not for edge direction, which the participants' own exposes/uses edges carry."
        },
        "conforms-to": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "standard": { "type": "string", "minLength": 1 },
              "version": { "type": "string" },
              "url": { "type": "string" }
            },
            "required": ["standard"]
          }
        }
      },
      "required": ["style", "participants"]
    },
    {
      "title": "actor",
      "properties": {
        "kind": { "const": "actor" },
        "actor-type": {
          "type": "string",
          "enum": ["human", "system", "external-system", "service-account"]
        },
        "goals": {
          "type": "array",
          "minItems": 1,
          "items": { "$ref": "#/$defs/one-line" }
        }
      },
      "required": ["actor-type", "goals"]
    },
    {
      "title": "environment",
      "properties": {
        "kind": { "const": "environment" },
        "environment-type": {
          "type": "string",
          "enum": ["dev", "staging", "production", "edge", "local"]
        }
      },
      "required": ["environment-type"]
    },
    {
      "title": "adr",
      "properties": {
        "kind": { "const": "adr" },
        "decision-status": {
          "type": "string",
          "enum": ["proposed", "accepted", "rejected", "superseded"],
          "description": "Where the decision stands in the architecture. Orthogonal to \`status\`, which is where the document stands."
        },
        "date": {
          "type": "string",
          "pattern": "^\\\\d{4}-\\\\d{2}-\\\\d{2}$",
          "description": "Bare ISO-8601 calendar date; no time, no timezone (E_ADR_DATE)."
        },
        "deciders": {
          "type": "array",
          "items": { "type": "string", "minLength": 1 },
          "description": "Who made the call. Conditionally REQUIRED and non-empty once a decision has actually been taken — an if/then this schema deliberately does not carry, because the spec gives the violation its own code (E_ADR_DECIDERS) and everything a schema rejects arrives as E_FM_SCHEMA."
        }
      },
      "required": ["decision-status", "date"]
    },
    {
      "title": "requirement",
      "properties": {
        "kind": { "const": "requirement" },
        "requirement-type": { "type": "string", "enum": ["functional", "non-functional"] },
        "priority": {
          "type": "string",
          "enum": ["must", "should", "could", "wont"],
          "description": "MoSCoW, spelled without an apostrophe."
        }
      },
      "required": ["requirement-type", "priority"]
    },
    {
      "title": "capability",
      "properties": {
        "kind": { "const": "capability" }
      },
      "description": "The one branch that adds nothing, and that is a decision rather than a placeholder. What the business can do is stated by \`title\` and \`summary\`; whether it is real is answered by the incoming \`realizes\` edges, which are derived. A branch with no fields is still load-bearing here: the root \`unevaluatedProperties: false\` means every kind field of every other kind is rejected on a capability."
    },
    {
      "title": "journey",
      "properties": {
        "kind": { "const": "journey" },
        "actor": {
          "$ref": "#/$defs/srn-ref",
          "description": "The protagonist, and the journey's defining relationship. Exactly one — a list is E_FM_SCHEMA. That it MUST resolve to an entity of kind \`actor\` is E_JRN_ACTOR_KIND, a catalog-level check no schema can make. The ordered steps are not here: they live in the sibling \`journey.yaml\`, because order does not survive in frontmatter."
        }
      },
      "required": ["actor"]
    },
    {
      "title": "metric",
      "properties": {
        "kind": { "const": "metric" },
        "metric-type": {
          "type": "string",
          "enum": ["ratio", "duration", "count", "amount"],
          "description": "The shape of the observation, not its subject matter — subject matter is an open facet and belongs in \`tags\`. The value selects the literal grammar \`target\` must be written in."
        },
        "target": {
          "$ref": "#/$defs/short-line",
          "description": "The line the observation is compared against, as a literal of the grammar \`metric-type\` selects (\\"99.9%\\", \\"400ms\\", \\"1200\\", \\"12.50 EUR\\"). A plain string here on purpose: the grammar violation is E_MET_TARGET, a code of its own, so encoding the four patterns would report it as E_FM_SCHEMA instead. Keeping it a string is also what makes an unquoted \`target: 1200\` fail as a type error."
        },
        "window": {
          "$ref": "#/$defs/short-line",
          "description": "\`instant\` for a gauge, or a rolling duration ending now (ms/s/m/h/d). No calendar tokens — a month is not a fixed duration. A malformed literal is E_MET_WINDOW, again a code of its own rather than E_FM_SCHEMA."
        },
        "direction": {
          "type": "string",
          "enum": ["higher-is-better", "lower-is-better"],
          "description": "Whether \`target\` is a floor or a ceiling. Spelled out rather than higher/lower, which on its own invites \\"higher than what?\\"."
        }
      },
      "required": ["metric-type", "target", "window", "direction"]
    }
  ],
  "unevaluatedProperties": false,
  "$defs": {
    "kebab": {
      "type": "string",
      "pattern": "^[a-z0-9]+(-[a-z0-9]+)*$",
      "minLength": 1,
      "maxLength": 64,
      "description": "Naming and the SRN share one grammar, because the path is the SRN."
    },
    "one-line": {
      "type": "string",
      "minLength": 1,
      "maxLength": 200,
      "pattern": "^[^\\\\n]*$"
    },
    "short-line": {
      "type": "string",
      "minLength": 1,
      "maxLength": 40,
      "pattern": "^[^\\\\n]*$"
    },
    "srn-ref": {
      "type": "string",
      "minLength": 1,
      "description": "An absolute srn:// reference, a solution-absolute path starting with /, or a relative path resolved from the referring entity's own directory. An optional @N pin may follow. An artifact SRN — a dot suffix on the final segment, as in \`…/protocol/order-placement.transport\` — is fenced out of every frontmatter reference surface, because every surface here means an entity and an artifact has no kind; the fence is E_FM_EDGE_TARGET on an edge, and its own code on each kind's own reference surfaces."
    },
    "relations": {
      "type": "object",
      "description": "Typed outgoing edges only. The seven inverses — used-by, exposed-by, depended-on-by, implemented-by, realized-by, measured-by, superseded-by — are derived by the portal and authoring one is E_FM_SCHEMA. The edge set is closed and grows by appending: \`realizes\` and \`measures\` arrived with the capability/journey/metric kinds and nothing existing moved.",
      "properties": {
        "uses": {
          "type": "array",
          "items": { "$ref": "#/$defs/srn-ref" },
          "description": "Any source. Targets: datamodel, protocol, environment, component."
        },
        "exposes": {
          "type": "array",
          "items": { "$ref": "#/$defs/srn-ref" },
          "description": "Source: component or product. Targets: protocol, datamodel."
        },
        "depends-on": {
          "type": "array",
          "items": { "$ref": "#/$defs/srn-ref" },
          "description": "Source: component or product. Targets: component, product."
        },
        "implements": {
          "type": "array",
          "items": { "$ref": "#/$defs/srn-ref" },
          "description": "Source: component or product. Target: requirement, and nothing else."
        },
        "supersedes": {
          "type": "array",
          "items": { "$ref": "#/$defs/srn-ref" },
          "description": "Any source; the target MUST be the same kind as the source."
        },
        "realizes": {
          "type": "array",
          "items": { "$ref": "#/$defs/srn-ref" },
          "description": "Source: component or product. Target: capability, and nothing else. Points up, from a built thing to a standing ability of the business — never the other way, which is why a capability authors nothing. Not \`implements\` in different clothes: a requirement is an obligation that can be checked off, a capability is never \\"done\\"."
        },
        "measures": {
          "type": "array",
          "items": { "$ref": "#/$defs/srn-ref" },
          "description": "Source: metric, and nothing else — the only edge restricted to one source kind. Targets: capability, component, protocol, requirement. Deliberately not \\"any\\": an actor, an environment and an adr are a person, a place and a past decision rather than parts of the system. A metric with no \`measures\` edge is E_MET_NO_SUBJECT, the only relation edge any kind requires — and a rule this schema cannot state, because \`relations\` itself is optional for every other kind."
        }
      },
      "additionalProperties": false
    }
  }
}
`,
    'metaframework/product/specification/datamodel/journey-document': `{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.metaframework.dev/metaframework/product/specification/datamodel/journey-document",
  "x-srn": "srn://metaframework/product/specification/datamodel/journey-document",
  "title": "Journey document",
  "description": "journey.yaml — one actor's path across the solution, in order: a flat list of 2 to 12 steps, no ids, no branches. Specified in framework/spec/kinds/journey.md; parsed by framework/portal/src/lib/journey/journey.ts.",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string",
      "minLength": 1,
      "description": "The dialect discriminator (0015-artifact-dialects); the canonical value is this schema's own $id. Deliberately unpinned rather than const: a value naming some other dialect is W_ARTIFACT_DIALECT, a warning, read as the legacy dialect and never broken — a const here would restate that ruling as a hard rejection in the one place a severity cannot be relaxed. The loader strips the key before parseJourney is handed the document, so nothing in the catalog depends on the parser tolerating it. parseJourney admits it regardless: $schema is listed in KNOWN_FILE_KEYS beside name and steps, at the top level only, so a caller holding raw file bytes and no loader — a fixture, an editor, a consumer reading this schema — gets the legacy dialect read rather than E_JRN_SCHEMA on the header this schema tells them to write. Admitted by name and not by widening the x- hatch: x- is the author's namespace and stays open-ended, $schema is one framework-owned literal, so the parser's set of legal top-level keys grew by exactly one and every other unknown key is still an error."
    },
    "name": {
      "type": "string",
      "pattern": "^[a-z0-9]+(-[a-z0-9]+)*$",
      "maxLength": 64,
      "description": "MUST equal the entity's name, i.e. its directory name (E_JRN_NAME) — the filename is fixed, so it carries no identity. Checked against the entity and never against the filename stem: a file copied into the wrong entity directory says so instead of silently becoming that entity's path."
    },
    "steps": { "$ref": "#/$defs/steps" }
  },
  "required": ["name", "steps"],
  "patternProperties": {
    "^x-": {
      "description": "The escape hatch reaches into this artifact, at the top level and inside a step. Tolerated and ignored by the portal; any other unknown key is E_JRN_SCHEMA. There is no title and no summary — index.md already carries both, and a second copy in the artifact would only drift — and no top-level version: the entity's frontmatter governs the whole directory."
    }
  },
  "additionalProperties": false,
  "$defs": {
    "steps": {
      "type": "array",
      "minItems": 2,
      "maxItems": 12,
      "items": { "$ref": "#/$defs/step" },
      "description": "The list order IS the order: no order key, no step ids, no timestamps, no durations. Both bounds are errors and not warnings (E_JRN_STEP_COUNT) — one step is a touch rather than a path, twelve rows is where the derived ladder stops fitting one screen, and a cap that only warns is a cap every catalog eventually ignores. The portal's stable key for a step is its positional path, steps[3], 0-based."
    },
    "step": {
      "type": "object",
      "description": "A described position, not an observed event. Exactly four keys are recognised, and each step carries its own subject: actor is written on every step rather than defaulting from the frontmatter protagonist, because a hand-off is the row a reader most needs to see and a field that defaults is a field that hides its exceptions.",
      "properties": {
        "actor": {
          "$ref": "#/$defs/srn-ref",
          "description": "Who takes this step. MUST resolve to an entity of kind actor (E_JRN_ACTOR_KIND). The frontmatter protagonist MUST be the actor of at least one step (W_JRN_ACTOR_ABSENT); every other actor here is a counterpart the path hands off to or waits on."
        },
        "touches": {
          "$ref": "#/$defs/srn-ref",
          "description": "What they touch. MUST resolve to a component or a product (E_JRN_TOUCHES_KIND). Its owning product — the product/{name} pair at the head of the pair chain — is what makes a product crossing decidable from the grammar alone."
        },
        "protocol": {
          "description": "How the step reaches what it touches. Three states, not two: an SRN resolving to a protocol (E_JRN_PROTOCOL_KIND); the literal none, the documented negative, meaning the actor carries the crossing and there is nothing to write down; or omitted, meaning not written down yet — which on a product crossing is W_JRN_UNDOCUMENTED_INTEGRATION, the check the kind exists for.",
          "anyOf": [
            { "title": "the documented negative", "const": "none" },
            { "title": "a protocol reference", "$ref": "#/$defs/srn-ref" }
          ]
        },
        "note": {
          "type": "string",
          "minLength": 1,
          "maxLength": 200,
          "pattern": "^[^\\\\n]+$",
          "description": "One line, display only, rendered as a note anchored to the step. The place a fork in the path is named, since the second branch is a second journey."
        }
      },
      "required": ["actor", "touches"],
      "patternProperties": { "^x-": {} },
      "additionalProperties": false,
      "not": {
        "description": "A journey is exactly one linear sequence. A branch-shaped key gets its own error class (E_JRN_BRANCH) rather than the generic E_JRN_SCHEMA, because the code is the lesson: a journey that branches is two journeys. The distinction is a diagnostic class and not a validity difference, so this clause restates a rejection additionalProperties already makes — what it adds is the seven names.",
        "anyOf": [
          { "required": ["alt"] },
          { "required": ["opt"] },
          { "required": ["loop"] },
          { "required": ["when"] },
          { "required": ["otherwise"] },
          { "required": ["branches"] },
          { "required": ["parallel"] }
        ]
      }
    },
    "srn-ref": {
      "type": "string",
      "minLength": 1,
      "maxLength": 240,
      "description": "An ordinary SRN reference, absolute or relative, resolved from the entity's own directory and never crossing into another solution. A journey sits at solution level and points almost entirely outward, so the solution-absolute form (/product/shop/component/checkout) is the readable one everywhere. Version pins parse but SHOULD be omitted — a pinned component would freeze the description of a thing that is still moving. An artifact suffix is refused on every step field (JRN16): a step means an entity, and an artifact has no kind."
    }
  }
}
`,
    'metaframework/product/specification/datamodel/schema-document': `{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.metaframework.dev/metaframework/product/specification/datamodel/schema-document",
  "x-srn": "srn://metaframework/product/specification/datamodel/schema-document",
  "title": "Schema document",
  "description": "The profile a catalog schema.json must satisfy: JSON Schema draft 2020-12, a canonical $id equal to the entity's schema URL, a required x-srn, no nested $id, and four forbidden keywords at any depth. Specified in framework/spec/kinds/datamodel.md; validated by framework/portal/src/lib/schema/registry.ts. Note that the prohibitions are stated as \`not\`/\`required\` rather than as false-valued property schemas: a schema.json may not carry a member named $anchor at any depth, and that includes the member of a \`properties\` map.",
  "type": "object",
  "properties": {
    "$schema": {
      "const": "https://json-schema.org/draft/2020-12/schema",
      "description": "Exactly one dialect. Anything else is E_DM_DIALECT."
    },
    "$id": {
      "type": "string",
      "pattern": "^https://schemas\\\\.metaframework\\\\.dev/[a-z0-9]+(-[a-z0-9]+)*(/[a-z0-9]+(-[a-z0-9]+)*)*$",
      "description": "The entity's canonical schema URL: the constant host followed by the entity's SRN path verbatim. No version suffix — a URL addresses the current schema. A deployment's own serving address — a localhost origin with the portal's schema-serving path under it — is E_DM_ID_MISMATCH; identity does not vary by deployment (decision-record amendment 2026-08-19-d). The address itself is not spelled here, because a catalog artifact that names one is exactly what fixture-check.test.ts forbids."
    },
    "x-srn": {
      "type": "string",
      "pattern": "^srn://[a-z0-9]+(-[a-z0-9]+)*(/[a-z0-9]+(-[a-z0-9]+)*)*$",
      "description": "The entity's unversioned SRN, stated so a schema lifted out of the catalog still says where it came from. Checked against the file's own directory, so it cannot drift from $id."
    },
    "title": { "type": "string" },
    "description": { "type": "string" },
    "deprecated": {
      "type": "boolean",
      "description": "The standard 2020-12 meta-data keyword. SHOULD be true at the root when the entity's frontmatter status is deprecated, so the annotation reaches consumers that only ever see the schema."
    },
    "$defs": {
      "type": "object",
      "additionalProperties": { "$ref": "#/$defs/subschema" },
      "description": "Entity-private. A $ref from another document into these is E_DM_FOREIGN_DEFS."
    },
    "allOf": {
      "type": "array",
      "items": { "$ref": "#/$defs/subschema" },
      "description": "Root-level allOf branches that $ref other datamodels are the entire inheritance layer. There is no extends, no x-inherits, no portal-side merge directive."
    },
    "properties": {
      "type": "object",
      "additionalProperties": { "$ref": "#/$defs/subschema" }
    },
    "oneOf": { "type": "array", "items": { "$ref": "#/$defs/subschema" } },
    "anyOf": { "type": "array", "items": { "$ref": "#/$defs/subschema" } },
    "items": { "$ref": "#/$defs/subschema" }
  },
  "required": ["$schema", "$id", "x-srn"],
  "not": {
    "anyOf": [
      { "required": ["$dynamicRef"] },
      { "required": ["$dynamicAnchor"] },
      { "required": ["$anchor"] },
      { "required": ["$vocabulary"] }
    ]
  },
  "$defs": {
    "no-forbidden-keywords": {
      "description": "$dynamicRef and $dynamicAnchor make the inheritance graph non-static, so the portal cannot derive it. $anchor is a second way to address a local shape, and #/$defs pointers stay greppable while anchors do not. $vocabulary is dialect authoring, and the dialect is fixed. All four are E_DM_KEYWORD.",
      "not": {
        "anyOf": [
          { "required": ["$dynamicRef"] },
          { "required": ["$dynamicAnchor"] },
          { "required": ["$anchor"] },
          { "required": ["$vocabulary"] }
        ]
      }
    },
    "subschema": {
      "description": "Any schema below the root. The four forbidden keywords are forbidden at every depth, and $id is forbidden everywhere except the root — a nested $id would re-base every reference beneath it onto a second identity, which is how one document quietly becomes two (E_DM_ID_FORBIDDEN).",
      "type": ["object", "boolean"],
      "allOf": [
        { "$ref": "#/$defs/no-forbidden-keywords" },
        { "not": { "required": ["$id"] } }
      ],
      "properties": {
        "$ref": { "$ref": "#/$defs/reference" },
        "$defs": { "type": "object", "additionalProperties": { "$ref": "#/$defs/subschema" } },
        "properties": { "type": "object", "additionalProperties": { "$ref": "#/$defs/subschema" } },
        "allOf": { "type": "array", "items": { "$ref": "#/$defs/subschema" } },
        "oneOf": { "type": "array", "items": { "$ref": "#/$defs/subschema" } },
        "anyOf": { "type": "array", "items": { "$ref": "#/$defs/subschema" } },
        "items": { "$ref": "#/$defs/subschema" }
      }
    },
    "reference": {
      "type": "string",
      "description": "Exactly two legal forms. A local JSON Pointer into this document's own $defs, or the canonical schema URL of another datamodel in the same solution. A relative file path, an srn:// URI, a serving address or a foreign host is E_DM_REF_TARGET; a URL that leaves the solution is E_SRN_CROSS_SOLUTION; a URL naming no registered datamodel is E_SRN_DANGLING.",
      "anyOf": [
        { "title": "local pointer", "pattern": "^#/\\\\$defs/" },
        {
          "title": "canonical schema URL",
          "pattern": "^https://schemas\\\\.metaframework\\\\.dev/[a-z0-9]+(-[a-z0-9]+)*(/[a-z0-9]+(-[a-z0-9]+)*)*$"
        }
      ]
    }
  }
}
`,
    'metaframework/product/specification/datamodel/state-machine-document': `{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.metaframework.dev/metaframework/product/specification/datamodel/state-machine-document",
  "x-srn": "srn://metaframework/product/specification/datamodel/state-machine-document",
  "title": "State machine document",
  "description": "states.json — an XState v5 machine configuration describing the state of one conversation as the protocol sees it, not the internal state of any participant. Pinned to a subset that createMachine() accepts verbatim. Specified in framework/spec/kinds/protocol.md; validated by framework/portal/src/lib/protocol/states.ts.",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string",
      "minLength": 1,
      "description": "The dialect discriminator (0015-artifact-dialects); the canonical value is this schema's own $id. Deliberately unpinned rather than const: a value naming some other dialect is W_ARTIFACT_DIALECT, a warning, read as the legacy dialect and never broken — a const here would restate that ruling as a hard rejection in the one place a severity cannot be relaxed. The loader strips the key before parseStates is handed the document, which is why the pinned subset stays exactly an XState config and E_PROTO_STATES_SUBSET stays strict."
    },
    "id": {
      "type": "string",
      "description": "MUST equal the protocol entity's name (E_PROTO_STATES_ID). It is also the root of every absolute target path, e.g. #order-placement.rejected."
    },
    "initial": {
      "type": "string",
      "description": "A key of this object's own states."
    },
    "states": { "$ref": "#/$defs/state-map" },
    "description": { "type": "string" }
  },
  "required": ["id", "initial", "states"],
  "additionalProperties": false,
  "$defs": {
    "state-map": {
      "type": "object",
      "propertyNames": { "pattern": "^[a-z0-9]+(-[a-z0-9]+)*$" },
      "additionalProperties": { "$ref": "#/$defs/state" },
      "minProperties": 1
    },
    "state": {
      "description": "A state node. \`additionalProperties: false\` is where the subset is enforced: context, assign, always, after, invoke, input, output and meta have no member here, and any of them is E_PROTO_STATES_SUBSET. The catalog documents contracts, not runtime behaviour — anything carrying data or executing is out.",
      "type": "object",
      "properties": {
        "states": { "$ref": "#/$defs/state-map" },
        "initial": {
          "type": "string",
          "description": "REQUIRED if and only if this node has states — a compound state must say where it begins."
        },
        "type": {
          "const": "final",
          "description": "The only legal value. type: parallel and type: history are outside the subset. A final state MUST carry no \`on\`."
        },
        "on": { "$ref": "#/$defs/transitions" },
        "entry": { "$ref": "#/$defs/actions" },
        "exit": { "$ref": "#/$defs/actions" },
        "tags": {
          "type": "array",
          "items": { "type": "string", "pattern": "^[a-z0-9]+(-[a-z0-9]+)*$" }
        },
        "description": { "type": "string" }
      },
      "additionalProperties": false,
      "dependentRequired": { "states": ["initial"] }
    },
    "transitions": {
      "type": "object",
      "description": "Event name to transition. Event names MUST match ^[A-Z][A-Z0-9_]*$ (E_PROTO_STATES_EVENT_NAME), which excludes the wildcard \\"*\\" by construction. An event name maps to a workflow message name by lowercasing and turning _ into -; one with no such message anywhere in the protocol's workflows raises W_PROTO_STATES_EVENT_UNKNOWN.",
      "propertyNames": { "pattern": "^[A-Z][A-Z0-9_]*$" },
      "additionalProperties": { "$ref": "#/$defs/transition-value" }
    },
    "transition-value": {
      "description": "A target string, a transition object, or an array of transition objects evaluated top to bottom — first matching guard wins, and an unguarded entry is the fallback.",
      "anyOf": [
        { "$ref": "#/$defs/target" },
        { "$ref": "#/$defs/transition" },
        { "type": "array", "items": { "$ref": "#/$defs/transition" }, "minItems": 1 }
      ]
    },
    "transition": {
      "type": "object",
      "properties": {
        "target": { "$ref": "#/$defs/target" },
        "guard": {
          "type": "string",
          "description": "A plain string, rendered as [guard] on the edge. Object-form guards are outside the subset."
        },
        "actions": { "$ref": "#/$defs/actions" },
        "description": { "type": "string" }
      },
      "additionalProperties": false
    },
    "target": {
      "type": "string",
      "description": "Exactly two forms (E_PROTO_STATES_TARGET otherwise): a sibling state key such as \\"reserved\\", or an absolute id path such as \\"#order-placement.rejected\\". Relative descent (\\"reserved.settled\\") is not supported — it is the form that most often silently resolves to the wrong node. Omitting target entirely makes the transition an internal self-transition: actions run, the machine does not move.",
      "anyOf": [
        { "title": "sibling state key", "pattern": "^[a-z0-9]+(-[a-z0-9]+)*$" },
        { "title": "absolute id path", "pattern": "^#[a-z0-9]+(-[a-z0-9]+)*(\\\\.[a-z0-9]+(-[a-z0-9]+)*)*$" }
      ]
    },
    "actions": {
      "description": "Action names as plain strings. Object-form actions, and assign in particular, are outside the subset — they carry data, and data shapes belong to datamodels.",
      "anyOf": [
        { "type": "string" },
        { "type": "array", "items": { "type": "string" } }
      ]
    }
  }
}
`,
    'metaframework/product/specification/datamodel/topology-document': `{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.metaframework.dev/metaframework/product/specification/datamodel/topology-document",
  "x-srn": "srn://metaframework/product/specification/datamodel/topology-document",
  "title": "Topology document",
  "description": "topology.yaml — where an environment's hosted components actually run: regions, zones, replica ranges and one sentence of scaling intent. A description for a reviewer, not an infrastructure manifest, and never a second membership channel. Specified in framework/spec/kinds/environment.md; no portal code parses it.",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string",
      "minLength": 1,
      "description": "The dialect discriminator (0015-artifact-dialects); the canonical value is this schema's own $id. Deliberately unpinned rather than const: a value naming some other dialect is W_ARTIFACT_DIALECT, a warning, read as the legacy dialect and never broken — a const here would restate that ruling as a hard rejection in the one place a severity cannot be relaxed. The loader strips the key once it has recorded the dialect, so nothing downstream ever sees it — including on the day something finally parses this file."
    },
    "regions": {
      "type": "array",
      "items": { "$ref": "#/$defs/region" },
      "description": "The regions this environment occupies. Absent means a single unnamed region — not an unknown one."
    },
    "hosts": {
      "type": "array",
      "items": { "$ref": "#/$defs/host" },
      "description": "Placement detail, one entry per hosted component or subtree. It ANNOTATES members and never creates them: membership is authored on the component side as a uses edge to this environment, and an entry for a component that does not declare it is W_ENV_HOST_UNDECLARED — a warning, because during a rollout the topology may legitimately lead the component's own declaration by a commit or two."
    }
  },
  "required": ["hosts"],
  "patternProperties": {
    "^x-": {
      "description": "The escape hatch reaches into this artifact, at the top level and inside entries. Tolerated and ignored by the portal; any other unknown key is E_ENV_TOPOLOGY_SCHEMA. No top-level version: both environment siblings are part of the entity's version snapshot and carry no version field of their own."
    }
  },
  "additionalProperties": false,
  "$defs": {
    "region": {
      "type": "object",
      "properties": {
        "name": {
          "$ref": "#/$defs/kebab",
          "description": "Unique within the file — a fact about the list, and therefore not statable here: uniqueItems compares whole entries, not one member of each. Free-form beyond the casing (eu-west-1, store-berlin)."
        },
        "zones": {
          "type": "array",
          "items": { "type": "string", "minLength": 1 },
          "description": "Failure domains inside the region ([a, b, c]). An empty list and an absent one are indistinguishable to this schema, though they are not the same claim — one catalog file says so in its own notes."
        },
        "notes": { "type": "string", "description": "Prose; may be multi-line. The only field here with no length bound." }
      },
      "required": ["name"],
      "patternProperties": { "^x-": {} },
      "additionalProperties": false
    },
    "host": {
      "type": "object",
      "properties": {
        "component": {
          "$ref": "#/$defs/srn-ref",
          "description": "MUST resolve to a component or a product (E_ENV_TARGET_KIND). A product target is shorthand for every component beneath it, with these settings; the most specific entry wins, so a subtree entry plus an explicit entry for one descendant is an override rather than a conflict."
        },
        "regions": {
          "type": "array",
          "items": { "$ref": "#/$defs/kebab" },
          "description": "Each name MUST be declared in the document's own regions list (E_ENV_REGION_UNKNOWN) — a cross-reference inside one document, which stock 2020-12 cannot make. Absent means placement is NOT RECORDED, and specifically not \\"everywhere\\"."
        },
        "replicas": { "$ref": "#/$defs/replicas" },
        "scaling": {
          "type": "string",
          "minLength": 1,
          "maxLength": 200,
          "pattern": "^[^\\\\n]+$",
          "description": "One human sentence: the trigger, not the YAML of an autoscaler."
        },
        "notes": { "type": "string", "description": "Prose; may be multi-line." }
      },
      "required": ["component"],
      "patternProperties": { "^x-": {} },
      "additionalProperties": false
    },
    "replicas": {
      "type": "object",
      "description": "A fixed count is { min: n, max: n } — the format has one way to write a number and it is a range with equal ends. min MUST be <= max (E_ENV_TOPOLOGY_SCHEMA), which is the one clause of ENV4 no stock 2020-12 document can state: comparing two sibling properties is outside the vocabulary.",
      "properties": {
        "min": { "type": "integer", "minimum": 0 },
        "max": { "type": "integer", "minimum": 0 }
      },
      "required": ["min", "max"],
      "patternProperties": { "^x-": {} },
      "additionalProperties": false
    },
    "kebab": {
      "type": "string",
      "pattern": "^[a-z0-9]+(-[a-z0-9]+)*$",
      "maxLength": 64
    },
    "srn-ref": {
      "type": "string",
      "minLength": 1,
      "description": "An ordinary SRN reference. Relative forms resolve against the artifact's own URI, srn://{solution}/environment/{name}/topology.yaml, so the solution-absolute form is strongly preferred — it is shorter and it survives the environment being renamed. An artifact suffix is refused (ENV11): hosts name entities, and an artifact has no kind."
    }
  }
}
`,
    'metaframework/product/specification/datamodel/transport-document': `{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.metaframework.dev/metaframework/product/specification/datamodel/transport-document",
  "x-srn": "srn://metaframework/product/specification/datamodel/transport-document",
  "title": "Transport document",
  "description": "transport.yaml — how one protocol's conversation reaches the wire. One protocol, one transport: the binding block is keyed by exactly the kind value, and \`spec\` and the block's surface list are mutually exclusive. Specified in framework/spec/kinds/protocol.md; no portal code parses it.",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string",
      "minLength": 1,
      "description": "The dialect discriminator (0015-artifact-dialects); the canonical value is this schema's own $id. Deliberately unpinned rather than const: a value naming some other dialect is W_ARTIFACT_DIALECT, a warning, read as the legacy dialect and never broken — a const here would restate that ruling as a hard rejection in the one place a severity cannot be relaxed. The loader strips the key before anything downstream is handed the document, which is why additionalProperties below still means what it says and E_PROTO_TRANSPORT_SCHEMA stays strict."
    },
    "kind": {
      "type": "string",
      "enum": ["http", "grpc", "amqp", "kafka", "websocket", "in-process"],
      "description": "The wire technology. Closed set; selects the binding block (E_PROTO_TRANSPORT_BINDING). No value exists for a local subprocess exec or for stdio JSON-RPC — both are recorded in prose and in x- keys instead."
    },
    "summary": { "type": "string", "minLength": 1, "maxLength": 200 },
    "encoding": {
      "type": "string",
      "enum": ["json", "avro", "protobuf", "msgpack", "xml", "text", "binary"],
      "description": "Wire encoding of payloads."
    },
    "auth": {
      "type": "array",
      "items": { "$ref": "#/$defs/kebab" },
      "description": "Display-only labels: oauth2-bearer, mtls, sasl-scram. The portal renders them and derives nothing."
    },
    "spec": { "$ref": "#/$defs/spec" },
    "http": { "$ref": "#/$defs/http-binding" },
    "grpc": { "$ref": "#/$defs/grpc-binding" },
    "amqp": { "$ref": "#/$defs/amqp-binding" },
    "kafka": { "$ref": "#/$defs/kafka-binding" },
    "websocket": { "$ref": "#/$defs/websocket-binding" },
    "in-process": { "$ref": "#/$defs/in-process-binding" }
  },
  "required": ["kind"],
  "patternProperties": {
    "^x-": {
      "description": "The escape hatch reaches into this artifact, at the top level and inside entries. Tolerated and ignored by the portal; any other unknown key is E_PROTO_TRANSPORT_SCHEMA."
    }
  },
  "additionalProperties": false,
  "dependentSchemas": {
    "spec": {
      "description": "spec and the binding block's surface list are mutually exclusive (E_PROTO_TRANSPORT_SPEC_CONFLICT): either the spec file is the single source of operation truth, or the lightweight list is written here. Maintaining both guarantees divergence.",
      "properties": {
        "http": { "not": { "required": ["operations"] } },
        "grpc": { "not": { "required": ["methods"] } },
        "amqp": { "not": { "required": ["bindings"] } },
        "kafka": { "not": { "required": ["topics"] } },
        "websocket": { "not": { "required": ["channels"] } },
        "in-process": { "not": { "required": ["functions"] } }
      }
    }
  },
  "allOf": [
    {
      "if": { "properties": { "kind": { "const": "http" } }, "required": ["kind"] },
      "then": {
        "required": ["http"],
        "not": { "anyOf": [{ "required": ["grpc"] }, { "required": ["amqp"] }, { "required": ["kafka"] }, { "required": ["websocket"] }, { "required": ["in-process"] }] }
      }
    },
    {
      "if": { "properties": { "kind": { "const": "grpc" } }, "required": ["kind"] },
      "then": {
        "required": ["grpc"],
        "not": { "anyOf": [{ "required": ["http"] }, { "required": ["amqp"] }, { "required": ["kafka"] }, { "required": ["websocket"] }, { "required": ["in-process"] }] }
      }
    },
    {
      "if": { "properties": { "kind": { "const": "amqp" } }, "required": ["kind"] },
      "then": {
        "required": ["amqp"],
        "not": { "anyOf": [{ "required": ["http"] }, { "required": ["grpc"] }, { "required": ["kafka"] }, { "required": ["websocket"] }, { "required": ["in-process"] }] }
      }
    },
    {
      "if": { "properties": { "kind": { "const": "kafka" } }, "required": ["kind"] },
      "then": {
        "required": ["kafka"],
        "not": { "anyOf": [{ "required": ["http"] }, { "required": ["grpc"] }, { "required": ["amqp"] }, { "required": ["websocket"] }, { "required": ["in-process"] }] },
        "allOf": [
          {
            "description": "kafka.topics is required unless an external spec is linked — the one binding block whose surface list is not optional.",
            "if": { "not": { "required": ["spec"] } },
            "then": { "properties": { "kafka": { "required": ["topics"] } } }
          }
        ]
      }
    },
    {
      "if": { "properties": { "kind": { "const": "websocket" } }, "required": ["kind"] },
      "then": {
        "required": ["websocket"],
        "not": { "anyOf": [{ "required": ["http"] }, { "required": ["grpc"] }, { "required": ["amqp"] }, { "required": ["kafka"] }, { "required": ["in-process"] }] }
      }
    },
    {
      "if": { "properties": { "kind": { "const": "in-process" } }, "required": ["kind"] },
      "then": {
        "required": ["in-process"],
        "not": { "anyOf": [{ "required": ["http"] }, { "required": ["grpc"] }, { "required": ["amqp"] }, { "required": ["kafka"] }, { "required": ["websocket"] }] }
      }
    }
  ],
  "$defs": {
    "kebab": {
      "type": "string",
      "pattern": "^[a-z0-9]+(-[a-z0-9]+)*$",
      "maxLength": 64
    },
    "srn-ref": {
      "type": "string",
      "description": "An SRN reference, absolute or solution-absolute, optionally @-pinned. MUST resolve to a datamodel (E_PROTO_PAYLOAD_KIND). This is one of the few places a version pin can still live, since a canonical schema URL cannot carry one."
    },
    "spec": {
      "type": "object",
      "description": "Link to an external spec file sitting beside index.md. In v1 the portal treats the linked file as an opaque attachment: a card with format, version and a raw link. Parsing OpenAPI or AsyncAPI to derive operation tables is deferred.",
      "properties": {
        "format": {
          "type": "string",
          "enum": ["openapi", "asyncapi", "protobuf", "graphql", "json-schema"]
        },
        "file": {
          "type": "string",
          "pattern": "^[^/]",
          "description": "Path relative to the entity directory. MUST exist, MUST NOT start with / and MUST NOT contain .. (E_PROTO_SPEC_FILE). Only the first of those three is checkable here; existence is not a schema question."
        },
        "version": { "type": "string" }
      },
      "required": ["format", "file"],
      "patternProperties": { "^x-": {} },
      "additionalProperties": false
    },
    "http-binding": {
      "type": "object",
      "properties": {
        "base-path": { "type": "string", "pattern": "^/", "description": "Path prefix all operations hang off." },
        "tls": { "type": "boolean", "default": true },
        "operations": {
          "type": "array",
          "items": { "$ref": "#/$defs/http-operation" },
          "description": "Surface list. Mutually exclusive with the document's spec."
        }
      },
      "required": ["base-path"],
      "patternProperties": { "^x-": {} },
      "additionalProperties": false
    },
    "http-operation": {
      "type": "object",
      "properties": {
        "name": { "$ref": "#/$defs/kebab" },
        "method": {
          "type": "string",
          "enum": ["GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS"]
        },
        "path": { "type": "string", "pattern": "^/", "description": "May contain {param} placeholders." },
        "request": { "$ref": "#/$defs/srn-ref" },
        "response": { "$ref": "#/$defs/srn-ref" },
        "summary": { "type": "string" }
      },
      "required": ["name", "method", "path"],
      "patternProperties": { "^x-": {} },
      "additionalProperties": false
    },
    "grpc-binding": {
      "type": "object",
      "properties": {
        "package": {
          "type": "string",
          "description": "Proto package, dot-separated. An external identifier, so not kebab-constrained."
        },
        "service": { "type": "string", "description": "Service name as declared in the proto." },
        "tls": { "type": "boolean", "default": true },
        "methods": { "type": "array", "items": { "$ref": "#/$defs/grpc-method" } }
      },
      "required": ["package", "service"],
      "patternProperties": { "^x-": {} },
      "additionalProperties": false
    },
    "grpc-method": {
      "type": "object",
      "properties": {
        "name": { "type": "string" },
        "request": { "$ref": "#/$defs/srn-ref" },
        "response": { "$ref": "#/$defs/srn-ref" },
        "streaming": { "type": "string", "enum": ["none", "client", "server", "bidi"], "default": "none" },
        "summary": { "type": "string" }
      },
      "required": ["name"],
      "patternProperties": { "^x-": {} },
      "additionalProperties": false
    },
    "amqp-binding": {
      "type": "object",
      "properties": {
        "exchange": { "type": "string", "description": "Exchange name; may be the empty string for the default exchange." },
        "exchange-type": { "type": "string", "enum": ["direct", "topic", "fanout", "headers"] },
        "durable": { "type": "boolean", "default": true },
        "bindings": { "type": "array", "items": { "$ref": "#/$defs/amqp-binding-entry" } }
      },
      "required": ["exchange", "exchange-type"],
      "patternProperties": { "^x-": {} },
      "additionalProperties": false
    },
    "amqp-binding-entry": {
      "type": "object",
      "properties": {
        "routing-key": { "type": "string", "description": "May contain * and # wildcards." },
        "queue": { "type": "string" },
        "message": { "$ref": "#/$defs/srn-ref" },
        "summary": { "type": "string" }
      },
      "required": ["routing-key", "queue"],
      "patternProperties": { "^x-": {} },
      "additionalProperties": false
    },
    "kafka-binding": {
      "type": "object",
      "properties": {
        "cluster": { "type": "string", "description": "Free label for the logical cluster." },
        "topics": { "type": "array", "items": { "$ref": "#/$defs/kafka-topic" } }
      },
      "patternProperties": { "^x-": {} },
      "additionalProperties": false
    },
    "kafka-topic": {
      "type": "object",
      "properties": {
        "name": { "type": "string", "description": "Kafka naming, not kebab-constrained." },
        "key": { "type": "string", "description": "The partition key." },
        "message": { "$ref": "#/$defs/srn-ref" },
        "partitions": { "type": "integer", "minimum": 1 },
        "retention": { "type": "string", "description": "e.g. 7d." },
        "summary": { "type": "string" }
      },
      "required": ["name"],
      "patternProperties": { "^x-": {} },
      "additionalProperties": false
    },
    "websocket-binding": {
      "type": "object",
      "properties": {
        "path": { "type": "string", "pattern": "^/", "description": "Upgrade path." },
        "subprotocol": { "type": "string", "description": "Sec-WebSocket-Protocol." },
        "tls": { "type": "boolean", "default": true },
        "channels": { "type": "array", "items": { "$ref": "#/$defs/websocket-channel" } }
      },
      "required": ["path"],
      "patternProperties": { "^x-": {} },
      "additionalProperties": false
    },
    "websocket-channel": {
      "type": "object",
      "properties": {
        "name": { "$ref": "#/$defs/kebab" },
        "direction": { "type": "string", "enum": ["client-to-server", "server-to-client", "bidi"] },
        "message": { "$ref": "#/$defs/srn-ref" },
        "summary": { "type": "string" }
      },
      "required": ["name", "direction"],
      "patternProperties": { "^x-": {} },
      "additionalProperties": false
    },
    "in-process-binding": {
      "type": "object",
      "properties": {
        "language": { "type": "string", "description": "e.g. typescript, python, go." },
        "module": { "type": "string", "description": "Import path or package path." },
        "interface": { "type": "string", "description": "Exported symbol implementing the surface." },
        "functions": { "type": "array", "items": { "$ref": "#/$defs/in-process-function" } }
      },
      "required": ["language", "module"],
      "patternProperties": { "^x-": {} },
      "additionalProperties": false
    },
    "in-process-function": {
      "type": "object",
      "properties": {
        "name": { "type": "string" },
        "request": { "$ref": "#/$defs/srn-ref" },
        "response": { "$ref": "#/$defs/srn-ref" },
        "summary": { "type": "string" }
      },
      "required": ["name"],
      "patternProperties": { "^x-": {} },
      "additionalProperties": false
    }
  }
}
`,
    'metaframework/product/specification/datamodel/workflow-document': `{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://schemas.metaframework.dev/metaframework/product/specification/datamodel/workflow-document",
  "x-srn": "srn://metaframework/product/specification/datamodel/workflow-document",
  "title": "Workflow document",
  "description": "One named, ordered exchange between a protocol's participants: workflows/<name>.yaml. Flat message steps by default, three named fragment forms for structure, nothing else. Specified in framework/spec/kinds/protocol.md; parsed by framework/portal/src/lib/protocol/workflow.ts.",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string",
      "minLength": 1,
      "description": "The dialect discriminator (0015-artifact-dialects); the canonical value is this schema's own $id. Deliberately unpinned rather than const: a value naming some other dialect is W_ARTIFACT_DIALECT, a warning, read as the legacy dialect and never broken — a const here would restate that ruling as a hard rejection in the one place a severity cannot be relaxed. The loader strips the key before parseWorkflow is handed the document, so nothing in the catalog depends on the parser tolerating it. parseWorkflow admits it regardless: workflowFileSchema is still a strict object and now carries $schema as an optional non-empty string at the root and nowhere else, so a caller holding raw file bytes and no loader — a fixture, an editor, a consumer reading this schema — gets the legacy dialect read rather than E_PROTO_WF_SCHEMA on the header this schema tells them to write. This format has no x- hatch and the header did not smuggle one in: one framework-owned literal was added to an enumerable set of root keys, so a misspelled steps: is still an error where an open extension point would have swallowed it."
    },
    "name": {
      "type": "string",
      "pattern": "^[a-z0-9]+(-[a-z0-9]+)*$",
      "description": "MUST equal the filename stem (E_PROTO_WF_NAME)."
    },
    "title": { "type": "string", "minLength": 1, "maxLength": 80 },
    "summary": { "type": "string", "minLength": 1, "maxLength": 200 },
    "participants": {
      "type": "array",
      "items": { "$ref": "#/$defs/alias" },
      "description": "Lifeline order. A layout hint, never a restriction: an alias used in a step but not listed here is appended after the listed ones. MUST be a subset of the protocol's own participant aliases (E_PROTO_WF_ALIAS)."
    },
    "steps": { "$ref": "#/$defs/steps" }
  },
  "required": ["name", "title", "steps"],
  "additionalProperties": false,
  "$defs": {
    "alias": {
      "type": "string",
      "pattern": "^[a-z0-9]+(-[a-z0-9]+)*$",
      "maxLength": 32,
      "description": "A participant alias declared in the protocol's index.md. The alias namespace is the protocol's, never the workflow's."
    },
    "steps": {
      "type": "array",
      "minItems": 1,
      "items": { "$ref": "#/$defs/step" },
      "description": "Every steps list — the workflow's own and every fragment's — MUST hold at least one step (E_PROTO_WF_EMPTY_BRANCH)."
    },
    "step": {
      "description": "Exactly one discriminator key from message, alt, opt, loop (E_PROTO_WF_STEP_SHAPE). \`otherwise\` is the one permitted companion key, and only alongside \`alt\`. Steps have no ids: the portal's stable key is the positional path, e.g. steps[4].alt[0].steps[2].",
      "type": "object",
      "oneOf": [
        { "$ref": "#/$defs/message-step" },
        { "$ref": "#/$defs/alt-step" },
        { "$ref": "#/$defs/opt-step" },
        { "$ref": "#/$defs/loop-step" }
      ]
    },
    "message-step": {
      "title": "message",
      "type": "object",
      "properties": {
        "message": {
          "type": "string",
          "pattern": "^[a-z0-9]+(-[a-z0-9]+)*$",
          "maxLength": 64,
          "description": "Logical message name; the arrow label."
        },
        "from": { "$ref": "#/$defs/alias" },
        "to": {
          "description": "One alias, or a list of aliases when kind is event. A list on a non-event step is E_PROTO_WF_FANOUT. from and to MAY be the same alias — a self-call.",
          "anyOf": [{ "$ref": "#/$defs/alias" }, { "type": "array", "items": { "$ref": "#/$defs/alias" } }]
        },
        "kind": {
          "type": "string",
          "enum": ["call", "return", "event", "error"],
          "default": "call"
        },
        "payload": {
          "type": "string",
          "description": "An SRN reference that MUST resolve to a datamodel (E_PROTO_PAYLOAD_KIND) and SHOULD carry an @version pin — this is one of the few places a pin can still live, since a schema URL cannot carry one."
        },
        "channel": {
          "type": "string",
          "description": "Topic, queue, routing key or path. Cross-checked against the transport's surface list when one exists (W_PROTO_WF_CHANNEL_UNKNOWN); the check is skipped entirely when transport.yaml is absent or links an external spec instead."
        },
        "condition": {
          "type": "string",
          "maxLength": 120,
          "description": "A display-only guard label on one arrow. It creates no branch — this is the most common authoring mistake in the format, and alt or opt is what changes the sequence."
        },
        "note": { "type": "string", "maxLength": 200 }
      },
      "required": ["message", "from", "to"],
      "additionalProperties": false
    },
    "alt-step": {
      "title": "alt",
      "description": "Mutually exclusive branches. At least two compartments, counting otherwise as one (E_PROTO_WF_SCHEMA): alt with a single branch and no otherwise is an opt, and the two mean different things.",
      "type": "object",
      "properties": {
        "alt": {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "object",
            "properties": {
              "when": { "type": "string", "maxLength": 120 },
              "steps": { "$ref": "#/$defs/steps" }
            },
            "required": ["when", "steps"],
            "additionalProperties": false
          }
        },
        "otherwise": { "$ref": "#/$defs/steps" }
      },
      "required": ["alt"],
      "additionalProperties": false
    },
    "opt-step": {
      "title": "opt",
      "description": "A single conditional branch: the steps may be skipped.",
      "type": "object",
      "properties": {
        "opt": {
          "type": "object",
          "properties": {
            "when": { "type": "string", "maxLength": 120 },
            "steps": { "$ref": "#/$defs/steps" }
          },
          "required": ["when", "steps"],
          "additionalProperties": false
        }
      },
      "required": ["opt"],
      "additionalProperties": false
    },
    "loop-step": {
      "title": "loop",
      "type": "object",
      "properties": {
        "loop": {
          "type": "object",
          "properties": {
            "while": { "type": "string", "maxLength": 120 },
            "max": { "type": "integer", "minimum": 1 },
            "steps": { "$ref": "#/$defs/steps" }
          },
          "required": ["while", "steps"],
          "additionalProperties": false
        }
      },
      "required": ["loop"],
      "additionalProperties": false
    }
  }
}
`,
  })
